# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-31 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0004_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('qualification', models.CharField(max_length=1000)),
                ('reg_no', models.IntegerField()),
                ('pt_ref', models.IntegerField()),
            ],
        ),
    ]
