# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-31 05:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0005_adddoctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddDoctor',
        ),
    ]
